title: Codeballoon
email: elliot.nelson@codeballoon.com
description: >
  Codeballoon is the personal website and brainspace of Elliot Nelson, a perpetually
  optimistic software engineer fascinated by all things math, logic, programming and design.
baseurl: ""
url: "http://codeballoon.com"
twitter_username: elliot-nelson
github_username:  codeballoon
timezone: America/Detroit
markdown: kramdown
